Client/Areas/Admin/Controllers/BrandController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace Client.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BrandController : Controller
    {


        private readonly HttpClient _httpClient;
        private readonly INotyfService _notyf;
        private readonly List<string> AllApi;

        public BrandController(HttpClient httpClient, INotyfService notyf)
        {
            _httpClient = httpClient;
            _notyf = notyf;
            // Khởi tạo danh sách API 
            AllApi = new List<string>
    {
        "https://localhost:7294/api/Brand/get-all",
        "https://localhost:7294/api/Brand/post",
        "https://localhost:7294/api/Brand/getbyid/",
        "https://localhost:7294/api/Brand/put/",
        "https://localhost:7294/api/Brand/delete/",
    };

        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {

            var response = await _httpClient.GetAsync(AllApi[0]);//Gửi yêu cầu
            if (response.IsSuccessStatusCode)
            {
                var responseData = await response.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<List<Brand>>(responseData);
                return View(data);
            }
            else
            {
                _notyf.Error(response.StatusCode.ToString());
                return View();
            }
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Brand item)
        {

            var jsonData = JsonConvert.SerializeObject(item);

            var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

            var responese = await _httpClient.PostAsync(AllApi[1], content);
            if (responese.IsSuccessStatusCode)
            {
                _notyf.Success("Thêm thành công!");
                 return Redirect("~/Admin/Brand/GetAll");
            }
            _notyf.Error("Lỗi!");
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var response = await _httpClient.GetFromJsonAsync<Brand>(AllApi[2] + $"{id}");
            if (response != null)
            {
                return View(response);
            }
            _notyf.Error("Not Found!");
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, Brand item)
        {

            var result = await _httpClient.PutAsJsonAsync<Brand>(AllApi[3] + $"{id}", item);
            if (result.IsSuccessStatusCode)
            {
                _notyf.Success("Update success!");
                 return Redirect("~/Admin/Brand/GetAll");
            }
            _notyf.Error($"Error: {result.StatusCode.ToString()}"!);
            return View();
        }
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _httpClient.DeleteAsync(AllApi[4] + $"{id}");
            if (result.IsSuccessStatusCode)
            {
                _notyf.Success("Delete success!");
                 return Redirect("~/Admin/Brand/GetAll");
            }
            _notyf.Error($"Error: {result.StatusCode.ToString()}"!);
            return View();

        }
    }
}

Client/Areas/Admin/Views/Brand/Create.cshtml
@model Data.Models.Brand

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h4 class="card-title">Create a Brand</h4>
    </div>
    <div class="card-body">
        <form asp-action="Create" asp-area="Admin" class="forms-sample">
            <div class="mb-3">
                <label asp-for="Name" class="form-label">Brand Name</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Status" class="form-label">Brand Code</label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a asp-action="GetAll" class="btn btn-light">Cancel</a>
            </div>
        </form>
    </div>
</div>

Client/Areas/Admin/Views/Brand/Edit.cshtml
@model Data.Models.Brand

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h4 class="card-title">Edit Brand</h4>
    </div>
    <div class="card-body">
        <form asp-action="Edit" asp-area="Admin" class="forms-sample">
            <div class="mb-3">
                <label asp-for="Name" class="form-label">Brand Name</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Status" class="form-label">Brand Status</label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a asp-action="GetAll" class="btn btn-light">Cancel</a>
            </div>
        </form>
    </div>
</div>

Client/Areas/Admin/Views/Brand/GetAll.cshtml
@model IEnumerable<Data.Models.Brand>

@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h4 class="card-title">List of Brands</h4>
    </div>
    <div class="card-body">
        <a class="btn btn-success" asp-controller="Brand" asp-action="Create">
            Create New
        </a>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Create date</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                <td>@Html.DisplayFor(modelItem => item.CreateDate)</td>
                                <td>@Html.DisplayFor(modelItem => item.Status)</td>
                                <td>
                                    <a class="btn btn-primary" asp-controller="Brand" asp-action="Edit" asp-route-id="@item.Id">
                                         Edit
                                    </a>
                                    <a class="btn btn-danger" asp-controller="Brand"  asp-area="Admin" asp-action="Delete" asp-route-id="@item.Id">
                                         Delete
                                    </a>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="4" class="text-center">
                                No Data.
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>