Client/Areas/Admin/Controllers/AddressController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace Client.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class AddressController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly INotyfService _notyf;
        private readonly List<string> AllApi;

        public AddressController(HttpClient httpClient, INotyfService notyf)
        {
            _httpClient = httpClient;
            _notyf = notyf;
            // Khởi tạo danh sách API 
            AllApi = new List<string>
        {
            "https://localhost:7294/api/Address/get-all",
            "https://localhost:7294/api/Address/post",
            "https://localhost:7294/api/Address/getbyid/",
            "https://localhost:7294/api/Address/put/",
            "https://localhost:7294/api/Address/delete/",
        };

        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {

            var response = await _httpClient.GetAsync(AllApi[0]);//Gửi yêu cầu
            if (response.IsSuccessStatusCode)
            {
                var responseData = await response.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<List<Address>>(responseData);
                return View(data);
            }
            else
            {
                _notyf.Error(response.StatusCode.ToString());
                return View();
            }
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Address item)
        {

            var jsonData = JsonConvert.SerializeObject(item);

            var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

            var responese = await _httpClient.PostAsync(AllApi[1], content);
            if (responese.IsSuccessStatusCode)
            {
                _notyf.Success("Thêm thành công!");
                 return Redirect("~/Admin/Address/GetAll");
            }
            _notyf.Error("Lỗi!");
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var response = await _httpClient.GetFromJsonAsync<Address>(AllApi[2] + $"{id}");
            if (response != null)
            {
                return View(response);
            }
            _notyf.Error("Not Found!");
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Edit(Guid id,Address item)
        {

            var result = await _httpClient.PutAsJsonAsync<Address>(AllApi[3] + $"{id}", item);
            if (result.IsSuccessStatusCode)
            {
                _notyf.Success("Update success!");
                 return Redirect("~/Admin/Address/GetAll");
            }
            _notyf.Error($"Error: {result.StatusCode.ToString()}"!);
            return View();
        }
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _httpClient.DeleteAsync(AllApi[4] + $"{id}");
            if (result.IsSuccessStatusCode)
            {
                _notyf.Success("Delete success!");
                 return Redirect("~/Admin/Address/GetAll");
            }
            _notyf.Error($"Error: {result.StatusCode.ToString()}"!);
            return View();

        }
        
    }
}

Client/Areas/Admin/Views/Address/Create.cshtml
@model Data.Models.Address

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="card">
    <div class="card-header">
        <h4 class="card-title">Create a Address</h4>
    </div>
    <div class="card-body">
        <form asp-action="Create" asp-area="Admin" class="forms-sample">
            <div class="mb-3">
                <label asp-for="City" class="form-label">City</label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="District" class="form-label">District</label>
                <input asp-for="District" class="form-control" />
                <span asp-validation-for="District" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Detailed_address" class="form-label">Detailed Address</label>
                <input asp-for="Detailed_address" class="form-control" />
                <span asp-validation-for="Detailed_address" class="text-danger"></span>
            </div>
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a asp-action="GetAll" class="btn btn-light">Cancel</a>
            </div>
        </form>
    </div>
</div>

Client/Areas/Admin/Views/Address/Edit.cshtml
@model Data.Models.Address

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>Address</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="District" class="control-label"></label>
                <input asp-for="District" class="form-control" />
                <span asp-validation-for="District" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wards" class="control-label"></label>
                <input asp-for="Wards" class="form-control" />
                <span asp-validation-for="Wards" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Detailed_address" class="control-label"></label>
                <input asp-for="Detailed_address" class="form-control" />
                <span asp-validation-for="Detailed_address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id_User" class="control-label"></label>
                <input asp-for="Id_User" class="form-control" />
                <span asp-validation-for="Id_User" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="card">
    <div class="card-header">
        <h4 class="card-title">Edit Address</h4>
    </div>
    <div class="card-body">
        <form asp-action="Edit" asp-area="Admin" class="forms-sample">
            <div class="mb-3">
                <label asp-for="City" class="form-label">Address City</label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="District" class="form-label"> District</label>
                <input asp-for="District" class="form-control" />
                <span asp-validation-for="District" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Wards" class="form-label"> Wards</label>
                <input asp-for="Wards" class="form-control" />
                <span asp-validation-for="Wards" class="text-danger"></span>
            </div>
            <div class="mt-3">
                <button type="submit"  class="btn btn-primary">Submit</button>
                <a asp-action="GetAll" class="btn btn-light">Cancel</a>
            </div>
        </form>
    </div>
</div>

Client/Areas/Admin/Views/Address/GetAll.cshtml
@model IEnumerable<Data.Models.Address>

@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="card">
    <div class="card-header">
        <h4 class="card-title">List of Addresss</h4>
    </div>
    <div class="card-body">
        <a class="btn btn-success" asp-controller="Address" asp-action="Create">
            Create New
        </a>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>District</th>
                        <th>City</th>
                        <th>Wards</th>
                        <th>Detailed Address</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.District)</td>
                                <td>@Html.DisplayFor(modelItem => item.City)</td>
                                <td>@Html.DisplayFor(modelItem => item.Wards)</td>
                                <td>@Html.DisplayFor(modelItem => item.Detailed_address)</td>
                                <td>
                                    <a class="btn btn-primary" asp-controller="Address" asp-action="Edit" asp-route-id="@item.Id">
                                        Edit
                                    </a>
                                    <a class="btn btn-danger" asp-controller="Address" asp-area="Admin" asp-action="Delete" asp-route-id="@item.Id">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="4" class="text-center">
                                No Data.
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>